name: Deploy

on:
  push:
    branches:
      - 21_1

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      CI: false
    strategy:
      matrix:
        theme: [ material.orange.light, material.orange.dark, generic.light, generic.dark ]
        mode: [ default, embedded ]

    steps:
    - name: Get sources
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Restore npm cache
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Run npm install
      run: npm install

    - name: Set theme
      run: npm run set-theme -- ${{ matrix.theme }}

    - name: Set theme
      if: ${{ matrix.mode == 'embedded' }}
      run: npm run make-embedded-mode

    - name: Run lerna
      run: npx lerna bootstrap

    - name: Build
      run: npm run build

    - name: Copy apps
      run: npm run copy-build -- ${{ matrix.mode }}

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        BRANCH: gh-pages
        FOLDER: devextreme-rwa-demos
        TARGET_FOLDER: ${{ matrix.theme }}

